import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/Layout";
import { experienceDuration } from "@/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Matt Rose",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap&"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&&display=swap"
          rel="stylesheet"
        />
        <meta
          name="description"
          content={`Full Stack Engineer with +${experienceDuration} of experience developing web applications.`}
        />
        {/* Google / Search Engine Tags */}
        <meta itemProp="name" content="Matt" />
        <meta
          itemProp="description"
          content={`Full Stack Engineer with +${experienceDuration} of experience developing web applications.`}
        />
        <meta
          itemProp="image"
          content="https://portfolio/images/avatars/1.jpg"
        />
        {/* Facebook Meta Tags */}
        <meta property="og:url" content="https://portfolio" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Matt" />
        <meta
          property="og:description"
          content={`Full Stack Engineer with +${experienceDuration} of experience developing web applications.`}
        />
        <meta
          property="og:image"
          content="https://portfolio/images/avatars/1.jpg"
        />
        {/* Twitter Meta Tags */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Matt" />
        <meta
          name="twitter:description"
          content={`Full Stack Engineer with +${experienceDuration} of experience developing web applications.`}
        />
        <meta
          name="twitter:image"
          content="https://portfolio/images/avatars/1.jpg"
        />
      </head>
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
